
require('dotenv').config();
const { 
    Client, GatewayIntentBits, Partials, SlashCommandBuilder, 
    Routes, REST, EmbedBuilder, ModalBuilder, TextInputBuilder, 
    TextInputStyle, ActionRowBuilder, ButtonBuilder, ButtonStyle 
} = require('discord.js');
const { Client: SelfbotClient } = require('discord.js-selfbot-v13');

const BOT_TOKEN = process.env.BOT_TOKEN;
const CLIENT_ID = process.env.CLIENT_ID;
const ALLOWED_GUILD_ID = "1493598034544820284"; // Allowed server restriction

const activeMonitors = new Map();

const bot = new Client({
    intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.DirectMessages],
    partials: [Partials.Channel]
});

const commands = [
    new SlashCommandBuilder()
        .setName('panel')
        .setDescription('Manage your target server log alerts.')
].map(command => command.toJSON());

const rest = new REST({ version: '10' }).setToken(BOT_TOKEN);

(async () => {
    try {
        console.log('Started refreshing application (/) commands.');
        await rest.put(Routes.applicationCommands(CLIENT_ID), { body: commands });
        console.log('Successfully reloaded application (/) commands.');
    } catch (error) {
        console.error('Error deploying commands:', error);
    }
})();

bot.once('ready', () => {
    console.log(`Bot logged in as ${bot.user.tag}`);
});

// Helper function to generate components dynamically based on tracking state
function getPanelComponents(userId, isRunning) {
    const btnStart = new ButtonBuilder()
        .setCustomId(`panel_start_${userId}`)
        .setLabel('Configure & Start')
        .setStyle(ButtonStyle.Primary)
        .setDisabled(isRunning); // Faded out if running

    const btnStop = new ButtonBuilder()
        .setCustomId(`panel_stop_${userId}`)
        .setLabel('Stop DM Alerts')
        .setStyle(ButtonStyle.Danger)
        .setDisabled(!isRunning); // Clickable only if running

    return new ActionRowBuilder().addComponents(btnStart, btnStop);
}

// Helper function to generate the dashboard layout profile embed mapping
function getPanelEmbed(userId, isRunning) {
    return new EmbedBuilder()
        .setTitle('⚙️ Join Logger Control Panel')
        .setDescription(`Manage your automated tracking settings below.\n\n**Owner:** <@${userId}>\n**Current Status:** ${isRunning ? '🟢 Active & Monitoring' : '🔴 Stopped'}`)
        .setColor(isRunning ? 0x00FF00 : 0xFF0000)
        .setTimestamp();
}

bot.on('interactionCreate', async interaction => {
    const userId = interaction.user.id;

    // A. Handle /panel command (With Server ID Whitelist Restriction)
    if (interaction.isChatInputCommand() && interaction.commandName === 'panel') {
        if (interaction.guildId !== ALLOWED_GUILD_ID) {
            return await interaction.reply({ 
                content: '❌ This command cannot be used in this server.', 
                ephemeral: true 
            });
        }

        const isRunning = activeMonitors.has(userId);
        const embed = getPanelEmbed(userId, isRunning);
        const row = getPanelComponents(userId, isRunning);
        
        return await interaction.reply({ embeds: [embed], components: [row] });
    }

    // B. Handle Component Action Interface Button Clicks
    if (interaction.isButton()) {
        const customId = interaction.customId;

        if (customId.startsWith('panel_start_') || customId.startsWith('panel_stop_')) {
            const panelOwnerId = customId.split('_')[2];

            if (userId !== panelOwnerId) {
                return await interaction.reply({ 
                    content: '❌ **Access Denied.** You cannot interact with a control panel generated by another user.', 
                    ephemeral: true 
                });
            }

            if (customId.startsWith('panel_start_')) {
                if (activeMonitors.has(userId)) {
                    return await interaction.reply({ 
                        content: '❌ **Session Conflict.** You already have an active tracker running.', 
                        ephemeral: true 
                    });
                }

                const modal = new ModalBuilder()
                    .setCustomId(`modal_${interaction.message.id}`) // Attach message ID to route back target updates
                    .setTitle('Target Server Configuration');

                const tokenInput = new TextInputBuilder()
                    .setCustomId('user_token')
                    .setLabel('User Token (Account in Target Server)')
                    .setStyle(TextInputStyle.Short)
                    .setPlaceholder('Paste your Discord account token here')
                    .setRequired(true);

                const serverIdInput = new TextInputBuilder()
                    .setCustomId('server_id')
                    .setLabel('Target Server ID')
                    .setStyle(TextInputStyle.Short)
                    .setPlaceholder('Enter the target server ID')
                    .setRequired(true);

                modal.addComponents(
                    new ActionRowBuilder().addComponents(tokenInput),
                    new ActionRowBuilder().addComponents(serverIdInput)
                );

                return await interaction.showModal(modal);
            }

            // Directly changes state back to stopped on the same panel view frame
            if (customId.startsWith('panel_stop_')) {
                if (activeMonitors.has(userId)) {
                    const selfbotToKill = activeMonitors.get(userId);
                    try { selfbotToKill.destroy(); } catch (e) {}
                    activeMonitors.delete(userId);

                    const embed = getPanelEmbed(userId, false);
                    const row = getPanelComponents(userId, false);
                    
                    // Updates existing layout panel framework components directly
                    return await interaction.update({ embeds: [embed], components: [row] });
                }
                return await interaction.reply({ content: '❌ You do not have any active tracking sessions running.', ephemeral: true });
            }
        }
    }

    // C. Handle Configuration Form Submissions
    if (interaction.isModalSubmit() && interaction.customId.startsWith('modal_')) {
        const targetMessageId = interaction.customId.split('_')[1];
        const userToken = interaction.fields.getTextInputValue('user_token');
        const serverId = interaction.fields.getTextInputValue('server_id');

        // Defer interaction payload instantly to confirm backend operation processes
        await interaction.deferUpdate();

        if (activeMonitors.has(userId)) {
            try { activeMonitors.get(userId).destroy(); } catch(e){}
            activeMonitors.delete(userId);
        }

        try {
            const selfbot = new SelfbotClient({ checkUpdate: false });
            activeMonitors.set(userId, selfbot);

            selfbot.on('guildMemberAdd', async (member) => {
                if (member.guild.id !== serverId) return;
                
                try {
                    const alertUser = await bot.users.fetch(userId);
                    const embed = new EmbedBuilder()
                        .setTitle('🚨 New Member Alert!')
                        .setDescription(`User **${member.user.tag || member.user.username}** joined the target server.`)
                        .addFields(
                            { name: 'User ID', value: member.user.id, inline: true },
                            { name: 'Account Created', value: `<t:${Math.floor(member.user.createdTimestamp / 1000)}:R>`, inline: true }
                        )
                        .setColor(0x00FF00)
                        .setTimestamp();

                    await alertUser.send({ embeds: [embed] });
                } catch (err) {
                    console.error('Failed to dispatch alert DM notice:', err);
                }
            });

            selfbot.once('ready', async () => {
                console.log(`Selfbot ready: ${selfbot.user.tag} active monitoring on server: ${serverId}`);
                
                // Immediately flip active styling states on the panel message frame
                try {
                    const targetChannel = await bot.channels.fetch(interaction.channelId);
                    const originalMessage = await targetChannel.messages.fetch(targetMessageId);
                    
                    const updatedEmbed = getPanelEmbed(userId, true);
                    const updatedRow = getPanelComponents(userId, true);

                    await originalMessage.edit({ embeds: [updatedEmbed], components: [updatedRow] });
                } catch (editError) {
                    console.error('Failed to update control panel message interface frame:', editError);
                }
            });

            await selfbot.login(userToken);

        } catch (error) {
            console.error('Selfbot Initialization error:', error);
            if (activeMonitors.has(userId)) activeMonitors.delete(userId);
        }
    }
});

bot.login(BOT_TOKEN);
